/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Logbook_2_Pipeline;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void isPalindrome() {
        // Arange
        App classUnderTest = new App();
        // Act and Assert
        assertEquals(classUnderTest.execute(), "Your sentence is a Palindrome!!!");

    }

    @Test public void isEmpty(){
        // Arange
        App classUnderTest1 = new App();
        // Act and Assert
        assertNotNull(classUnderTest1.execute(), "Your sentence is a Palindrome!!!");
    }
}
