/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Logbook_2_Pipeline;
import java.util.ArrayList;
import java.util.Arrays;
import java.lang.String;
public class App {
    public String execute() {
        //return "Hello World!";
        //SortingArray();
       return PalindromeHomePractice();
        //SortingArray();
    }
    public int execute2(){

        return SortingArrayMinMax();
    }

    public static void main(String[] args) {
        new App().execute();
        new App().execute2();
        System.out.println(new App().execute());
    }

    public static int SortingArrayMinMax(){
        //ArrayList<Integer> myArray = new ArrayList<>();
        //myArray.addAll(Arrays.asList());

        int[] myArray = {78, 53, 25, 42, 54, 11, 23, 55, 9, 33, 60, 666};
        int min = myArray[0], max = 0;

        for (int index = 0; index < myArray.length; index++) {
            if (min > myArray[index]) {
                min = myArray[index];
            }
            if (max < myArray[index]) {
                max = myArray[index];
            }




        }
        System.out.println("The min value in the array is: " + min);
        System.out.println("The max value in the array is: " + max);
        return max;
    }

    public static String PalindromeHomePractice() {
        String myPolidrome = "Tam taramtam matmarat maT";
        myPolidrome.replaceAll("\\s+","");
        char[] charArray = myPolidrome.toUpperCase().toCharArray(); //problems with the order of the shit
        char[] reverseArray = new char[charArray.length];           //toCharArraylast otherwise red light
        int letterCounter = 0;
        char letter;

        for (int index = 0; index < charArray.length; index++) {
            reverseArray[index] = charArray[charArray.length-index-1]; //this part reverses the shit
        }
        for(int index = 0; index<reverseArray.length; index++) {
            if(reverseArray[index] == charArray[index]) { //if the letters match counter++
                letterCounter++;
            }

        }if(letterCounter == reverseArray.length) //if the number of matches same as length Palindrome
          return "Your sentence is a Palindrome!!!";
        else
            return "Your sentence is not a Palindrome!!!";
    }
    public static void SortingArray() {
        ArrayList<Integer> myArray = new ArrayList<>();
        myArray.addAll(Arrays.asList(78, 53, 25, 42, 54,11, 23, 55, 9, 33, 60, 666));
        int temp;

        for (int i = 0; i < myArray.size(); i++)
            for (int j = i; j < myArray.size(); j++)
                if (myArray.get(i)>myArray.get(j)) {
                    temp = myArray.get(i);
                    myArray.set(i,myArray.get(j));
                    myArray.set(j,temp);
                }
        int min=myArray.get(0);
        int max=myArray.get(myArray.size()-1);



        System.out.println("The min value in the array is: " + min);
        System.out.println("The max value in the array is: " + max);
        System.out.println("Sorted array is: " + myArray);

        // TODO code application logic here
    }
}
