name: Gradle Java project Github Actions build.
# Define when the worklow should run. On a push to main, a PR to main or manually with workflow_dispatch

on:
  #push:
    #branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  #workflow_dispatch:

# Define some jobs that should run

jobs: 
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: 
          java-version: 8
      - name: Building with Gradle
        run: |
         chmod +x ./gradlew
         ./gradlew clean 
         ./gradlew clean build
         ./gradlew deploy
         echo "Deployment successfull!!!"
      - name: Creating a Build Scan
        run: ./gradlew build --scan
